# if you want change the data url if you change in config.yaml then it will reflect to all files.


artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_url: https://github.com/gauti5/branching-tutorial/raw/main/winequality-data.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion